### ISSUE TITLE
华为云创建接口缺少name参数

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#24]
华为云创建对等连接创建接口和NAT网关创建接口缺少name参数
华为云创建弹性公网ip缺少带宽名称参数

**Comment by yolanda0209** [comment]
华为云创建弹性公网ip需要增加可选的带宽名称入参

**Comment by yolanda0209** [comment]
lb target接口需要增加监听器名称和后端服务组名的可选入参

**Comment by brankbao** [comment]
已经添加，代码已经合并到master
