### ISSUE TITLE
华为云创建snat rule失败

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#32]
V1.1.2版本创建snat rule返回失败, 在V1.1.1版本测试是成功的。云上创建成功的。

![image](https://user-images.githubusercontent.com/17095701/78059717-f0401980-73bc-11ea-99b4-9b9f717ee6d1.png)
![image](https://user-images.githubusercontent.com/17095701/78059842-2a112000-73bd-11ea-9183-fbcfb3504a0a.png)

time="2020-04-01T01:59:01+08:00" level=info msg="path strings = [ huaweicloud v1 nat-gateway add-snat-rule]" func=main.parsePluginRequest file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:74"
time="2020-04-01T01:59:01+08:00" level=info msg="parsed request = {v1 huaweicloud nat-gateway add-snat-rule 0xc000068200}" func=main.parsePluginRequest file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:82"
time="2020-04-01T01:59:01+08:00" level=info msg="plguin[nat-gateway]-action[add-snat-rule] start..." func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:95"
time="2020-04-01T01:59:01+08:00" level=info msg="read parameters from http request = &{0xc00038e020 <nil> <nil> false true {0 0} false false false 0x69be30}" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:117"
time="2020-04-01T01:59:01+08:00" level=info msg="action do with parameters = {[{{0062_0000000001} {SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880 CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c} 0062_0000000001  09bb3ae7-c49c-4906-9e7f-a42bc011dd7d dd8b3b56-cf4d-4e16-9c53-b4bbd4eb3ef8 58829c53-b314-463c-ad17-ac72fc46a8a1}]}" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:123"
time="2020-04-01T01:59:04+08:00" level=error msg="create snat rule failed,err=json: cannot unmarshal number into Go struct field SnatRule.source_type of type string" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.addSnatRule file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/nat.go:404"
time="2020-04-01T01:59:04+08:00" level=info msg="all snat rule = {[{{0062_0000000001} {SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880 CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c} 0062_0000000001  09bb3ae7-c49c-4906-9e7f-a42bc011dd7d dd8b3b56-cf4d-4e16-9c53-b4bbd4eb3ef8 58829c53-b314-463c-ad17-ac72fc46a8a1}]} are created" func="github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.(*AddSnatRuleAction).Do" file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/nat.go:425"
time="2020-04-01T01:59:04+08:00" level=error msg="plguin[nat-gateway]-action[add-snat-rule] meet error = json: cannot unmarshal number into Go struct field SnatRule.source_type of type string" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process.func1 file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:85"
time="2020-04-01T01:59:04+08:00" level=info msg="write data to client response=&{ResultCode:1 ResultMsg:json: cannot unmarshal number into Go struct field SnatRule.source_type of type string Results:0xc00038e2e0}" func=main.routeDispatcher file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:58"

**Comment by TylerTang06** [comment]
这个问题 定位到了是 华为云的问题，sdk里的source_type以前是string，现在变成int了（他们的api文档里也变了）
