### ISSUE TITLE
华为云创建包月云服务器无返回超时

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#33]
华为云创建包月云服务器无返回超时，节点超时时间30分钟。
一次请求创建两台，一台包月，一台按需计费。等待30分钟请求无返回，实际云上创建成功一台按需计费的云主机，包月的主机未创建。
![image](https://user-images.githubusercontent.com/17095701/78066549-bcb6bc80-73c7-11ea-975b-91af5f105d0c.png)
![image](https://user-images.githubusercontent.com/17095701/78066563-c6402480-73c7-11ea-87cd-31f15155526f.png)
![image](https://user-images.githubusercontent.com/17095701/78067020-9a716e80-73c8-11ea-81ff-4287af79a8d0.png)

time="2020-04-01T02:47:36+08:00" level=info msg="action do with parameters = {[{{0032_0000000010} {SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880 CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c} 0032_0000000010  123456 5be19e6d-80ef-4e9d-96a2-ec1b8438065d 1C2G 50 a4ede0b8-5be4-467c-b483-c429e2a032fc dd8b3b56-cf4d-4e16-9c53-b4bbd4eb3ef8 172.16.0.2 hwhost2 Abcd1234  ap-southeast-1b  postPaid  0  } {{0032_0000000011} {SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880 CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c} 0032_0000000011  123456 5be19e6d-80ef-4e9d-96a2-ec1b8438065d 1C2G 50 a4ede0b8-5be4-467c-b483-c429e2a032fc dd8b3b56-cf4d-4e16-9c53-b4bbd4eb3ef8 172.16.0.3 hwhost3 Abcd1234  ap-southeast-1b  prePaid month 1  }]}" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:123"
time="2020-04-01T02:47:37+08:00" level=info msg="get instancetype=s3.medium.2" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.getFlavorByHostType file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/vm.go:374"
time="2020-04-01T02:48:26+08:00" level=info msg="get instancetype=s3.medium.2" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.getFlavorByHostType file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/vm.go:374"

**Comment by TylerTang06** [comment]
![image](https://user-images.githubusercontent.com/16753393/78095483-afbabd00-7409-11ea-8413-39fbf70fd093.png)
创建包年包月vm 出现的问题需要去界面 手动点支付，需要设置让它自动支付
