### ISSUE TITLE
在华为云香港区域创建1C1G规格的rds返回规格无效

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#42]
在华为云香港区域创建1C1G规格的rds返回规格无效。

插件创建的1c1g是规格 rds.mysql.c2.medium.rr mode 为repeat
香港区域的规格rds.mysql.c2.medium.rr mode 为single
包老师建议接口改成不自动，把云上的参数开出来

Request:

{"callbackParameter":"0033_0000000002",
"is_auto_renew":"",
"machine_spec":"1C1G",
"charge_type":"postPaid",
"volume_type":"ULTRAHIGH",
"seed":"123456",
"period_num":"0",
"vpc_id":"a4ede0b8-5be4-467c-b483-c429e2a032fc",
"security_group_id":"f2cf64fc-6847-4a55-9039-44619ab290e1",
"cloud_params":"CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c",
"engine_type":"MySQL",
"enterprise_project_id":"",
"password":"Abcd1234",
"identity_params":"SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880",
"port":"3306",
"name":"hwdb01",
"az":"ap-southeast-1a",
"guid":"0033_0000000002",
"subnet_id":"dbb2d5f0-a99a-4789-addb-7bc5af578c3f",
"volume_size":"40",
"id":"",
"engine_version":"5.6",
"period_type":""}

Response:

{"callbackParameter":"0033_0000000002",
"errorMessage":"{\"ErrorCode\":\"DBS.280239\",
\"Message\":\"Invalid specifications.\"}",
"errorCode":"1",
"guid":"0033_0000000002"}

**Comment by TylerTang06** [comment]
我测试 ok的
