### ISSUE TITLE
删云硬盘接口返回失败， 卸载了云主机但是没有删掉云硬盘

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#46]
[root@hwhost3 wecube-plugins-huaweicloud]# curl -X POST \
>   http://127.0.0.1:8083/huaweicloud/v1/block-storage/umount-delete \
>   -H 'cache-control: no-cache' \
>   -H 'content-type: application/json' \
>   -H 'postman-token: 645a73cc-2ce1-2738-c086-493a177db721' \
>   -d '{
>         "inputs":[
>                 {
>  "instance_guid":"0032_0000000010",
> "mount_dir":"/data/test",
> "seed":"123456",
> "attach_id":"ca7fcfd4-9064-4440-873e-669c9bb74f98",
> "volume_name":"/dev/vdb",
> "cloud_params":"CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c",
> "password":"{cipher_a}04122b0762c0b26cf210bf048f328310",
> "instance_id":"6ded12b7-387c-46d7-b6dc-373717055173",
> "identity_params":"SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880",
> "az":"ap-southeast-1b",
> "guid":"0036_0000000001",
> "id":"ca7fcfd4-9064-4440-873e-669c9bb74f98"
>                 }
>         ]
> }
> '
{"resultCode":"1","resultMessage":"{\"ErrorCode\":\"APIGW.0101\",\"Message\":\"The API does not exist or has not been published in the environment\"}","results":{"outputs":[{"errorCode":"1","errorMessage"[root@hwhost3 wecube-plugins-huaweicloud]#
![image](https://user-images.githubusercontent.com/17095701/78464364-23670d80-771b-11ea-89eb-8155245fd339.png)
time="2020-04-04T21:41:10+08:00" level=info msg="path strings = [ huaweicloud v1 block-storage umount-delete]" func=main.parsePluginRequest file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:74"
time="2020-04-04T21:41:10+08:00" level=info msg="parsed request = {v1 huaweicloud block-storage umount-delete 0xc0006340c0}" func=main.parsePluginRequest file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:82"
time="2020-04-04T21:41:10+08:00" level=info msg="plguin[block-storage]-action[umount-delete] start..." func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:96"
time="2020-04-04T21:41:10+08:00" level=info msg="read parameters from http request = &{0xc00021e020 <nil> <nil> false true {0 0} false false false 0x68c190}" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:118"
time="2020-04-04T21:41:10+08:00" level=info msg="action do with parameters = {[{{} {SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880 CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-1;ProjectId=07bfdaf7db8026f92f8dc01167f3a87c} 0036_0000000001 ap-southeast-1b ca7fcfd4-9064-4440-873e-669c9bb74f98 ca7fcfd4-9064-4440-873e-669c9bb74f98 6ded12b7-387c-46d7-b6dc-373717055173 0032_0000000010 123456 {cipher_a}04122b0762c0b26cf210bf048f328310 /data/test /dev/vdb}]}" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:124"
time="2020-04-04T21:41:17+08:00" level=error msg="plguin[block-storage]-action[umount-delete] meet error = {\"ErrorCode\":\"APIGW.0101\",\"Message\":\"The API does not exist or has not been published in the environment\"}" func=github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins.Process.func1 file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/plugins/plugins.go:86"
time="2020-04-04T21:41:17+08:00" level=info msg="write data to client response=&{ResultCode:1 ResultMsg:{\"ErrorCode\":\"APIGW.0101\",\"Message\":\"The API does not exist or has not been published in the environment\"} Results:{Outputs:[{CallBackParameter:{Parameter:} Result:{Code:1 Message:{\"ErrorCode\":\"APIGW.0101\",\"Message\":\"The API does not exist or has not been published in the environment\"}} Guid:0036_0000000001}]}}" func=main.routeDispatcher file="/data/gowork/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:58"
[root@hwhost3 logs]#

**Comment by brankbao** [comment]
问题已修复，已经合并到master
