### ISSUE TITLE
华为云数据库接口需要增加系统参数和接口入参

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#55]
华为云数据库接口需要增加系统参数和接口入参：
MYSQL_BACKUP_TYPE_LOGICAL 
 MYSQL_CHARACTER_SET
 MYSQL_LOWER_CASE_TABLE_NAMES |   |   | active

**Comment by brankbao** [comment]
这个华为云备份接口无MYSQL_BACKUP_TYPE_LOGICAL参数，不用支持

**Comment by TylerTang06** [comment]
done
