### ISSUE TITLE
创建云主机接口返回的memory大小和云上实际创建的云主机规格不一致

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#59]
创建云主机返回接口返回memory 2G 和云上页面显示的云服务器信息规格不一致， 云上页面显示1G。
![image](https://user-images.githubusercontent.com/17095701/78747944-528cb180-799d-11ea-9a8c-a11ba3e34a0d.png)
![image](https://user-images.githubusercontent.com/17095701/78747950-57516580-799d-11ea-8cd7-7b4082c38258.png)

**Comment by TylerTang06** [comment]
done
