### ISSUE TITLE
创建rds返回错误

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#62]
创建rds包月机器，报错缺少参数 Mode
![image](https://user-images.githubusercontent.com/17095701/78756384-4a3c7280-79ad-11ea-99eb-1c36dde38f0d.png)

{"callbackParameter":"0033_0000000003",
"is_auto_renew":null,
"machine_spec":"1C1G",
"support_ha":"false",
"charge_type":"prePaid",
"volume_type":"ULTRAHIGH",
"seed":"123456",
"period_num":"1",
"vpc_id":"96aa95c6-7492-4a6a-8b04-ccc7db64bb1b",
"security_group_id":"11cf2d43-05f9-401e-8e5e-ebcdb8003e80",
"cloud_params":"CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-3;ProjectId=07c34b94508010ff2fb3c011b4a986e3",
"ha_replication_mode":null,
"enterprise_project_id":"",
"password":"Abcd1234",
"identity_params":"SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880",
"port":"3306",
"name":"hwdb02",
"az":"ap-southeast-3b",
"guid":"0033_0000000003",
"subnet_id":"bd69cb3e-f421-4d68-bf5e-b7bfd2b175b0",
"volume_size":"40",
"id":"",
"engine_version":"5.7",
"period_type":"month"}

**Comment by TylerTang06** [comment]
done
