### ISSUE TITLE
华为云目前不支持创建包年包月rds，返回Com.200 error

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#68]
华为云目前不支持创建包年包月rds，COM.200 error
![image](https://user-images.githubusercontent.com/17095701/78882412-9ad5cd80-7a8a-11ea-9ea8-2c765b9d006a.png)

**Comment by irvinezhao** [comment]
依赖华为云工单，预计下下周末

**Comment by TylerTang06** [comment]
![image](https://user-images.githubusercontent.com/16753393/79086039-49b92880-7d6d-11ea-96ba-0a626830be30.png)

**Comment by TylerTang06** [comment]
华为云sdk bug已修复，目前可以创建rds mysql包年包月实例

**Comment by TylerTang06** [comment]
未支付情况下，查询不到实例信息
