### ISSUE TITLE
华为云创建4.0redis失败，engine type不支持

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-huaweicloud#79]
插件调用返回
time="2020-04-13T19:15:09+08:00" level=info msg="write data to client response=&{ResultCode:1 ResultMsg:Bad request with: [POST https://dcs.ap-southeast-3.myhuaweicloud.com/v1.0/07c34b94508010ff2fb3c011b4a986e3/instances], error message: {\"error\":{\"code\":\"111400007\",\"message\":\"The selected cache engine type is not supported.\",\"ext_message\":null}} Results:{Outputs:[{CallBackParameter:{Parameter:0034_0000000005} Result:{Code:1 Message:Bad request with: [POST https://dcs.ap-southeast-3.myhuaweicloud.com/v1.0/07c34b94508010ff2fb3c011b4a986e3/instances], error message: {\"error\":{\"code\":\"111400007\",\"message\":\"The selected cache engine type is not supported.\",\"ext_message\":null}}} Guid:0034_0000000005 Id: PrivateIp: Password:}]}}" func=main.routeDispatcher file="/go/src/github.com/WeBankPartners/wecube-plugins-huaweicloud/main.go:57"

插件调用入参
{"callbackParameter":"0034_0000000005",
"is_auto_renew":"",
"charge_type":"postPaid",
"seed":"123456",
"period_num":"1",
"vpc_id":"64c34707-e3ed-41e5-a819-ab1cfd7d5a36",
"security_group_id":"d7fd8cc1-347c-4bf8-a040-ace39a554055",
"cloud_params":"CloudApiDomainName=myhuaweicloud.com;Region=ap-southeast-3;ProjectId=07c34b94508010ff2fb3c011b4a986e3",
"private_ip":"172.18.0.4",
"capacity":"2",
"password":"Abcd1234",
"identity_params":"SecretKey=1dYRU1DBVaYKSixG0kcw2kqIehgEGlEdT4nb7dLN;AccessKey=Y361GSQB7SZPTRBZVAWI;DomainId=07bfdaf7d00026f90f8ac01118d2e880",
"name":"redis02",
"az":"ap-southeast-3b",
"guid":"0034_0000000005",
"subnet_id":"57b879cf-3188-4b24-be00-6fbc7ead6ead",
"id":"",
"engine_version":"4.0",
"instance_type":"single",
"period_type":""}

**Comment by brankbao** [comment]
提工单确认，对方回复如下：

**Comment by brankbao** [comment]
【华为云】尊敬的hw60048060，您提交的工单TS202004134221工程师进行了回复：  “您好，很抱歉让您久等了，这边在官网上看，4.0和5.0是不支持指定ip的，3.0可以选择自己指定ip地址，因为3.0底层用的是ecs资源，4.0和5.0用的是物理机资源，差别应该在这，按您测试的结果看应该是这个原因”；请您及时查看，如有疑问请在工单中继续反馈，感谢您对华为云的支持！

**Comment by brankbao** [comment]
原因为4.0和5.0的redis不支持指定IP

**Comment by brankbao** [comment]
代码已合并master
